---

- name: VM QEMU/KVM create
  hosts: localhost
  connection: local
  become: true
  tasks:
    # ##############################################
    # Create:
    #   - Networks
    #   - Storage Pools
    #   - Virtual machines
    #   - Snapshots
    # ##############################################
    # # https://serverfault.com/questions/434064/correct-way-to-move-kvm-vm
    # - https://unix.stackexchange.com/questions/628454/how-can-i-migrate-backup-restore-a-virt-manager-snapshot
    # - https://www.libvirt.org/manpages/virsh.html#storage-pool-commands
    # - https://computingforgeeks.com/virsh-commands-cheatsheet-kvm/#3-storage-management
    # - https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/9/html/configuring_and_managing_virtualization/
    # - https://www.tecmint.com/manage-kvm-storage-volumes-and-pools/

    # ### #######
    # ### Network
    # ### #######

    # - name: VM - Ensure that 'default' network is active (Qemu-Kvm)
    #   community.libvirt.virt_net:
    #     state: active # ansonsten läuft nächster Schritt "destroy/undefine default virtual network" auf Fehler
    #     name: default
    #   # - ansible_facts['virtualization_role'] != "guest"

    # - name: VM - start 'default' virtual network (Qemu-Kvm)
    #   tags: VM
    #   ansible.builtin.shell:
    #     cmd: virsh net-start default
    #   args:
    #     creates: "{{ env_home }}/.ansible_vm_qemuKvmCreated"
    #   ignore_errors: true
    #   when:
    #   # - ansible_facts['virtualization_role'] != "guest"
    #
    #   # error: internal error: Network is already in use by interface enp1s0
    #   # -> wenn Rechner/VM und 'default' virtuel Network (i.d.R.) 192.168.122.0/24 -> z.B. 'default' subnet ändern

    # da alle virtuellen Netzwerke aus den dump-files erstellt werden und 'default' dann schon da wäre (-> Fehlermeldung)
    - name: VM - undefine 'default' virtual network (Qemu-Kvm, Arch)
      tags: VM
      ansible.builtin.command:
        cmd: virsh net-undefine default
        # cmd: set -o pipefail && virsh net-destroy default --force && virsh net-undefine default
        #      # 'default' initial nicht gestartet, daher auch nicht stoppen mit net-destroy
      args:
        creates: "{{ env_home }}/.ansible_vm_qemuKvmCreated"
      # ignore_errors: true # Reminder to delete default net manually
      when:
        - ansible_facts['distribution'] in ["Archlinux"]
      #   - ansible_facts['virtualization_role'] != "guest"

    # ---------------------------------------------------
    - name: VM - create virtual networks (Qemu-Kvm, Arch)
      tags: VM
      ansible.builtin.shell:
        cmd: set -o pipefail && ls files/VM/netdump_*.xml | xargs -I % sh -c "virsh net-define %" # inkl. Pfad
        # executable: /bin/bash
        # oder:
        # chdir: files/VM/
        # cmd: ls netdump_*.xml | xargs -I % sh -c "virsh net-define %"
      args:
        creates: "{{ env_home }}/.ansible_vm_qemuKvmCreated"
      # ignore_errors: true # da 'default' schon/noch da
      when:
        - ansible_facts['distribution'] in ["Archlinux"]
      #   - ansible_facts['virtualization_role'] != "guest"

    - name: VM - create virtual networks (Qemu-Kvm, not Arch)
      tags: VM
      ansible.builtin.shell:
        cmd: set -o pipefail && ls files/VM/netdump_*.xml | grep -v "netdump_default.xml" | xargs -I % sh -c "virsh net-define %" # inkl. Pfad
      args:
        creates: "{{ env_home }}/.ansible_vm_qemuKvmCreated"
      when:
        - ansible_facts['distribution'] not in ["Archlinux"]
    # ---------------------------------------------------

    # da alle virt. Netw. auf autostart + rechner sowiese neugestartet werden muss: auskommentiert
    # - name: VM - start all virtual networks (Qemu-Kvm)
    #   tags: VM
    #   ansible.builtin.shell:
    #     chdir: files/VM/
    #     cmd: set -o pipefail && ls netdump_*.xml | xargs -I % sh -c "echo % | cut -d _ -f 2" | xargs -I % sh -c "echo % | \
    #              cut -d . -f 1" | xargs -I % sh -c "virsh net-start %"
    #     # z.B.: netdump_default.xml   default.xml   default   virsh net-start default
    #   args:
    #     creates: "{{ env_home }}/.ansible_vm_qemuKvmCreated"
    #   ignore_errors: true # u.a.: Failed to start network default\nerror: internal error: Network is already in use by interface enp1s0
    #   #                   # +: Fehler bei den anderen in zusammenhang mit Firewall
    #   when:
    #     - ansible_facts['virtualization_role'] != "guest"

    - name: VM - autostart all virtual networks (Qemu-Kvm, Arch)
      tags: VM
      ansible.builtin.shell:
        chdir: files/VM/
        cmd: >
          set -o pipefail &&
          ls netdump_*.xml |
          xargs -I % sh -c "echo % | cut -d _ -f 2" |
          xargs -I % sh -c "echo % | cut -d . -f 1" |
          xargs -I % sh -c "virsh net-autostart %"
      args:
        creates: "{{ env_home }}/.ansible_vm_qemuKvmCreated"
      # ignore_errors: true
      when:
        - ansible_facts['distribution'] in ["Archlinux"]
      #   - ansible_facts['virtualization_role'] != "guest"

    # "default" Network already available + autostart
    - name: VM - autostart all virtual networks (Qemu-Kvm, not Arch)
      tags: VM
      ansible.builtin.shell:
        chdir: files/VM/
        cmd: >
          set -o pipefail &&
          ls netdump_*.xml | grep -v "netdump_default.xml" |
          xargs -I % sh -c "echo % | cut -d _ -f 2" |
          xargs -I % sh -c "echo % | cut -d . -f 1" |
          xargs -I % sh -c "virsh net-autostart %"
      args:
        creates: "{{ env_home }}/.ansible_vm_qemuKvmCreated"
      when:
        - ansible_facts['distribution'] not in ["Archlinux"]

    # ### ############
    # ### storage pool
    # ### ############

    # Bluefin OS: "default" pool and "nvram" Pool already available
    - name: VM - storage pools - define pools (Qemu-Kvm)
      tags: VM
      ansible.builtin.shell:
        chdir: files/VM/
        cmd: >
          set -o pipefail &&
          ls pooldump_*.xml | grep -vE "pooldump_default.xml|pooldump_nvram.xml" |
          xargs -I % sh -c "virsh pool-define %"
      args:
        creates: "{{ env_home }}/.ansible_vm_qemuKvmCreated"
      # when:
      #   - ansible_facts['distribution'] not in ["Archlinux"]

    # not necessary in my case (for pools of type dir ?!)
    # - error: no source device defined
    # - pool-build replaced by just creating the folders (paths) for the storage pools (type: dir)
    # - -> virsh pool-start + virsh pool-autostart work
    #
    # creates pools physically # --no-overwrite: prevents overwriting existing data (more secure for existing pools)
    #
    # - name: VM - storage pools - build pools (Qemu-Kvm)
    #   tags: VM
    #   ansible.builtin.shell:
    #     chdir: files/VM/
    #     cmd: >
    #       set -o pipefail &&
    #       ls pooldump_*.xml | grep -v "pooldump_default.xml" |
    #       xargs -I % sh -c "echo % | cut -d _ -f 2" |
    #       xargs -I % sh -c "echo % | cut -d . -f 1" |
    #       xargs -I % sh -c "virsh pool-build % --no-overwrite"
    #   args:
    #     creates: "{{ env_home }}/.ansible_vm_qemuKvmCreated"
    #   # when:
    #   #   - ansible_facts['distribution'] not in ["Archlinux"]

    # Bluefin OS: "default" pool and "nvram" Pool already available
    - name: VM - storage pools - create target directories
      tags: VM
      ansible.builtin.shell:
        chdir: files/VM/
        cmd: >
          set -o pipefail &&
          for xml in pooldump_*.xml; do
            [ "$xml" = "pooldump_default.xml" ] && continue
            [ "$xml" = "pooldump_nvram.xml" ] && continue
            poolpath=$(yq '.pool.target.path' "$xml")
            [ -n "$poolpath" ] && mkdir -p "$poolpath"
          done
      args:
        creates: "{{ env_home }}/.ansible_vm_qemuKvmCreated"

    # Bluefin OS: "default" pool and "nvram" Pool already available / (auto-)started
    - name: VM - storage pools - start and activate pools (Qemu-Kvm)
      tags: VM
      ansible.builtin.shell:
        chdir: files/VM/
        cmd: >
          set -o pipefail &&
          ls pooldump_*.xml | grep -vE "pooldump_default.xml|pooldump_nvram.xml" |
          xargs -I % sh -c "echo % | cut -d _ -f 2" |
          xargs -I % sh -c "echo % | cut -d . -f 1" |
          xargs -I % sh -c "virsh pool-start % && virsh pool-autostart %"
      args:
        creates: "{{ env_home }}/.ansible_vm_qemuKvmCreated"
      # when:
      #   - ansible_facts['distribution'] not in ["Archlinux"]

    # ### ################
    # ### virtual machines
    # ### ################

    - name: VM - create virtual machines (Qemu-Kvm)
      tags: VM
      ansible.builtin.shell:
        chdir: files/VM/
        cmd: set -o pipefail && ls vmdump_*.xml | xargs -I % sh -c "virsh define %"
        # 'virsh define': just creates, does not start vm; 'virsh create': creates + starts vm
      args:
        creates: "{{ env_home }}/.ansible_vm_qemuKvmCreated"
      # ignore_errors: true
      # when:
      #   - ansible_facts['virtualization_role'] != "guest"

    # ### #########
    # ### snapshots
    # ### #########

    - name: VM - redefine + set current virtual machine snapshots (Qemu-Kvm)
      tags: VM
      ansible.builtin.command:
        chdir: files/VM/
        cmd: ./vm_snapshotcreate-redefine.sh
      args:
        creates: "{{ env_home }}/.ansible_vm_qemuKvmCreated"
      # ignore_errors: true
      # when:
      #   - ansible_facts['virtualization_role'] != "guest"

    # ### ####
    # ### flag
    # ### ####

    - name: VM - create 'flag-file' indicating VM-stuff was created (Qemu-Kvm)
      tags: VM
      ansible.builtin.file:
        path: "{{ env_home }}/.ansible_vm_qemuKvmCreated"
        state: touch
        owner: "{{ env_user }}"
        group: "{{ env_user }}"
        mode: "0644"
        modification_time: preserve
      # when:
      #   - ansible_facts['virtualization_role'] != "guest"
